config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      post :update_effort
      get :burndown
      get :burndown_graph
      get :stats
      post :sort
    end
    collection do
      get :burndown_index
      get :stats_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true do
    member do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
      get :release_plan
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "scrum/stats",
      :controller => :scrum, :action => :stats,
      :as => :scrum_stats

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/remaining_story_points",
     :controller => :scrum, :action => :change_remaining_story_points,
     :as => :change_remaining_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/pending_efforts",
     :controller => :scrum, :action => :change_pending_efforts,
     :as => :change_pending_efforts
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
get "issues/:id/time_entry",
     :controller => :scrum, :action => :new_time_entry,
     :as => :new_scrum_time_entry
post "issues/:id/time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_scrum_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:pbi_id/move/:position",
    :controller => :scrum, :action => :move_pbi,
    :as => :move_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:sprint_id/move_not_closed_pbis_to_last_sprint",
     :controller => :scrum, :action => :move_not_closed_pbis_to_last_sprint,
     :as => :move_not_closed_pbis_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

app/controllers/scrum_controller.rb
# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

class ScrumController < ApplicationController

  menu_item :product_backlog, :except => [:stats]
  menu_item :overview, :only => [:stats]

  before_filter :find_issue,
                :only => [:change_story_points, :change_remaining_story_points,
                          :change_pending_effort,
                          :change_assigned_to, :new_time_entry,
                          :create_time_entry, :edit_task, :update_task,
                          :change_pending_efforts]
  before_filter :find_sprint,
                :only => [:new_pbi, :create_pbi,
                          :move_not_closed_pbis_to_last_sprint]
  before_filter :find_pbi,
                :only => [:new_task, :create_task, :edit_pbi, :update_pbi,
                          :move_pbi, :move_to_last_sprint,
                          :move_to_product_backlog]
  before_filter :find_project_by_project_id,
                :only => [:stats]

  before_filter :authorize,
                :except => [:new_pbi, :create_pbi, :new_task, :create_task,
                            :move_to_last_sprint,
                            :move_not_closed_pbis_to_last_sprint,
                            :move_to_product_backlog,
                            :new_time_entry, :create_time_entry]
  before_filter :authorize_add_issues,
                :only => [:new_pbi, :create_pbi, :new_task, :create_task]
  before_filter :authorize_edit_issues,
                :only => [:move_to_last_sprint,
                          :move_not_closed_pbis_to_last_sprint,
                          :move_to_product_backlog]
  before_filter :authorize_log_time,
                :only => [:new_time_entry, :create_time_entry]

  helper :custom_fields
  helper :projects
  helper :scrum
  helper :timelog

  def change_story_points
    begin
      @issue.story_points = params[:value]
      status = 200
    rescue
      status = 503
    end
    render :nothing => true, :status => status
  end

  def change_remaining_story_points
    @issue.remaining_story_points = params[:value]
    render :nothing => true, :status => status
  end

  def change_pending_effort
    @issue.pending_effort = params[:value]
    render :nothing => true, :status => 200
  end

  def change_pending_efforts
    params['pending_efforts'].each_pair do |id, value|
      pending_effort = PendingEffort.find(id)
      raise "Invalid pending effort ID #{id}" if pending_effort.nil?
      raise "Pending effort ID #{id} is not owned by this issue" if pending_effort.issue_id != @issue.id
      if value.blank?
        pending_effort.delete
      else
        pending_effort.effort = value.to_f
        pending_effort.save!
      end
    end
    redirect_to issue_path(@issue)
  end

  def change_assigned_to
    @issue.init_journal(User.current)
    @issue.assigned_to = params[:value].blank? ? nil : User.find(params[:value].to_i)
    @issue.save!
    render_task(@project, @issue, params)
  end

  def new_time_entry
    @pbi_status_id = params[:pbi_status_id]
    @other_pbi_status_ids = params[:other_pbi_status_ids]
    @task_id = params[:task_id]
    respond_to do |format|
      format.js
    end
  end

  def create_time_entry
    begin
      time_entry = TimeEntry.new(params[:time_entry])
      time_entry.project_id = @project.id
      time_entry.issue_id = @issue.id
      time_entry.user_id = params[:time_entry][:user_id]
      call_hook(:controller_timelog_edit_before_save, {:params => params, :time_entry => time_entry})
      time_entry.save!
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def new_pbi
    @pbi = Issue.new
    @pbi.project = @project
    @pbi.tracker = @project.trackers.find(params[:tracker_id])
    @pbi.status = @pbi.default_status
    @pbi.author = User.current
    @pbi.sprint = @sprint
    @top = true unless params[:top].nil? or (params[:top] == 'false')
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create_pbi
    begin
      @continue = !(params[:create_and_continue].nil?)
      @top = !(params[:top].nil?)
      @pbi = Issue.new
      if params[:issue][:project_id]
        @pbi.project_id = params[:issue][:project_id]
      else
        @pbi.project = @project
      end
      @pbi.author = User.current
      @pbi.tracker_id = params[:issue][:tracker_id]
      @pbi.set_on_top if @top
      @pbi.sprint = @sprint
      update_attributes(@pbi, params)
      @pbi.save!
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_pbi
    respond_to do |format|
      format.js
    end
  end

  def update_pbi
    begin
      @pbi.init_journal(User.current, params[:issue][:notes])
      update_attributes(@pbi, params)
      @pbi.save!
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def move_pbi
    begin
      @position = params[:position]
      case params[:position]
        when 'top', 'bottom'
          @pbi.move_pbi_to(@position)
        when 'before'
          @other_pbi = params[:before_other_pbi]
          @pbi.move_pbi_to(@position, @other_pbi)
        when 'after'
          @other_pbi = params[:after_other_pbi]
          @pbi.move_pbi_to(@position, @other_pbi)
        else
          raise "Invalid position: #{@position.inspect}"
      end
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
  end

  def move_to_last_sprint
    begin
      raise "The project hasn't defined any Sprint yet" unless @project.last_sprint
      @previous_sprint = @pbi.sprint
      move_issue_to_sprint(@pbi, @project.last_sprint)
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def move_not_closed_pbis_to_last_sprint
    begin
      last_sprint = @project.last_sprint
      raise "The project hasn't defined any Sprint yet" unless last_sprint
      not_closed_pbis = @sprint.not_closed_pbis
      if not_closed_pbis.empty?
        flash[:notice] = l(:label_nothing_to_move)
      else
        not_closed_pbis_links = []
        not_closed_pbis.each do |pbi|
          link = view_context.link_to_issue(pbi,
                                            :project => pbi.project != @project,
                                            :tracker => true)
          not_closed_pbis_links << link
          move_issue_to_sprint(pbi, last_sprint)
        end
        flash[:notice] = l(:label_pbis_moved,
                           :pbis => not_closed_pbis_links.join(', '))
      end
    rescue Exception => exception
      logger.error("Exception: #{exception.inspect}")
      flash[:error] = exception
    end
    redirect_to sprint_path(@sprint)
  end

  def move_to_product_backlog
    begin
      product_backlog = @project.product_backlogs.find(params[:id])
      move_issue_to_sprint(@pbi, product_backlog)
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def new_task
    @task = Issue.new
    @task.project = @pbi.project
    @task.tracker = Tracker.find(params[:tracker_id])
    @task.status = @task.default_status
    @task.parent = @pbi
    @task.author = User.current
    @task.sprint = @sprint
    if Scrum::Setting.inherit_pbi_attributes
      @task.inherit_from_issue(@pbi)
    end
    respond_to do |format|
      format.html
      format.js
    end
  rescue Exception => e
    logger.error("Exception: #{e.inspect}")
    render_404
  end

  def create_task
    begin
      @continue = !(params[:create_and_continue].nil?)
      @task = Issue.new
      if params[:issue][:project_id]
        @task.project_id = params[:issue][:project_id]
      else
        @task.project = @pbi.project
      end
      @task.parent_issue_id = @pbi.id
      @task.author = User.current
      @task.sprint = @sprint
      @task.tracker_id = params[:issue][:tracker_id]
      update_attributes(@task, params)
      @task.save!
      @task.pending_effort = params[:issue][:pending_effort]
    rescue Exception => @exception
    end
    respond_to do |format|
      format.js
    end
  end

  def edit_task
    respond_to do |format|
      format.js
    end
  end

  def update_task
    begin
      @issue.init_journal(User.current, params[:issue][:notes])
      @old_status = @issue.status
      update_attributes(@issue, params)
      @issue.save!
      @issue.pending_effort = params[:issue][:pending_effort]
    rescue Exception => @exception
      logger.error("Exception: #{@exception.inspect}")
    end
    respond_to do |format|
      format.js
    end
  end

  def stats
    if User.current.allowed_to?(:view_time_entries, @project)
      cond = @project.project_condition(Setting.display_subprojects_issues?)
      @total_hours = TimeEntry.visible.where(cond).sum(:hours).to_f
    end

    @closed_story_points_per_sprint = @project.closed_story_points_per_sprint
    @closed_story_points_per_sprint_chart = {:id => 'closed_story_points_per_sprint', :height => 400}

    @hours_per_story_point = @project.hours_per_story_point
    @hours_per_story_point_chart = {:id => 'hours_per_story_point', :height => 400}

    @sps_by_pbi_category, @sps_by_pbi_category_total = @project.sps_by_category
    @sps_by_pbi_type, @sps_by_pbi_type_total = @project.sps_by_pbi_type

app/helpers/scrum_helper.rb
# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

module ScrumHelper

  include ProjectsHelper

  def render_pbi_left_header(pbi)
    parts = []
    if Scrum::Setting.render_position_on_pbi
      parts << "#{l(:field_position)}: #{pbi.position}"
    end
    if Scrum::Setting.render_category_on_pbi and pbi.category
      parts << "#{l(:field_category)}: #{h(pbi.category.name)}"
    end
    if Scrum::Setting.render_version_on_pbi and pbi.fixed_version
      parts << "#{l(:field_fixed_version)}: #{link_to_version(pbi.fixed_version)}"
    end
    render :inline => parts.join(", ")
  end

  def render_pbi_right_header(pbi)
    parts = []
    if Scrum::Setting.render_author_on_pbi
      parts << authoring(pbi.created_on, pbi.author)
    end
    if Scrum::Setting.render_updated_on_pbi and pbi.created_on != pbi.updated_on
      parts << "#{l(:label_updated_time, time_tag(pbi.updated_on))}"
    end
    render :inline => parts.join(", ")
  end

  def render_issue_icons(issue)
    icons = []
    if (User.current.allowed_to?(:view_time_entries, issue.project) and
        ((issue.is_pbi? and Scrum::Setting.render_pbis_speed) or
         (issue.is_task? and Scrum::Setting.render_tasks_speed)) and
        (speed = issue.speed))
      if speed <= Scrum::Setting.lowest_speed
        icons << render_issue_icon(LOWEST_SPEED_ICON, speed)
      elsif speed <= Scrum::Setting.low_speed
        icons << render_issue_icon(LOW_SPEED_ICON, speed)
      elsif speed >= Scrum::Setting.high_speed
        icons << render_issue_icon(HIGH_SPEED_ICON, speed)
      end
    end
    render :inline => icons.join('\n')
  end

  def project_selector_tree(project, indent = '')
    options = [["#{indent}#{project.name}", project.id]]
    project.children.visible.each do |child_project|
      options += project_selector_tree(child_project, indent + '» ')
    end
    return options
  end

  DEVIATION_ICONS = [LOWEST_SPEED_ICON = "icon-major-deviation",
                     LOW_SPEED_ICON = "icon-minor-deviation",
                     HIGH_SPEED_ICON = "icon-below-deviation"]

private

  def render_issue_icon(icon, speed)
    link_to("", "#", :class => "icon float-icon #{icon}",
            :title => l(:label_issue_speed, :speed => speed))
  end

end

app/views/scrum/_create_time_entry.html.erb
<h3 class="title"><%= l(:field_time_entries) %></h3>

<div id="time-entry-messages" />

<%= form_for :time_entry, :url => create_scrum_time_entry_path(@issue), :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= error_messages_for 'time_entry' %>
  <%= hidden_field_tag :pbi_status_id, @pbi_status_id %>
  <%= hidden_field_tag :other_pbi_status_ids, @other_pbi_status_ids %>
  <%= hidden_field_tag :task_id, @task_id %>
  <div class="box tabular">
    <p>
      <label><%= l(:field_hours) %>:</label>
      <%= f.text_field :hours, :size => 15, :required => true %>
    </p>

    <p>
      <label><%= l(:field_spent_on) %>:</label>
      <%= f.text_field :spent_on, :size => 10, :value => Date.today, :required => true %>
    </p>

    <p>
      <label><%= l(:field_comments) %>:</label>
      <%= f.text_field :comments, :size => 15, :maxlength => 255 %>
    </p>

    <p>
      <label><%= l(:field_activity) %>:</label>
      <%= f.select :activity_id,
                    @project.activities.collect{|activity| [activity.name, activity.id]},
                    :required => true %>
    </p>

    <p>
      <label><%= l(:field_user) %>:</label>
      <%= f.select :user_id,
                    principals_options_for_select(@issue.assignable_users, @issue.assigned_to),
                    :required => true %>
    </p>

    <%- TimeEntry.new.custom_field_values.each do |value| -%>
      <p>
        <label><%= value.custom_field.name %>:</label>
        <%= custom_field_tag :time_entry, value %>
      </p>
    <%- end -%>

    <p>
      <%= submit_tag l(:button_save) %>
    </p>
  </div>
<% end %>

app/views/scrum/_edit_issue_attributes.html.erb
<%= render :partial => "scrum/issue_attributes", :formats => [:html],
           :locals => {:f => f, :issue => issue} %>

<p class="buttons">
  <%= submit_tag l(:button_edit), :name => "edit", :disable_with => l(:label_loading) %>
  <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => "button" %>
</p>

app/views/scrum/_edit_pbi_modal.html.erb
<h3 class="title"><%= "#{@pbi.tracker.name} ##{@pbi.id}" %></h3>

<%- there_is_last_sprint = (!(@project.last_sprint.nil?))
    there_is_product_backlog = (!(@project.product_backlogs.empty?))
    render_move_to_last_sprint = (there_is_last_sprint and
                                  ((@pbi.sprint.is_product_backlog?) or (@pbi.sprint.id != @project.last_sprint.id)))
    render_move_to_product_backlog = (there_is_product_backlog and
                                     ((!(@project.product_backlogs.include?(@pbi.sprint))) or
                                      (@project.product_backlogs.size > 1)))
    render_move_pbi = (there_is_product_backlog and (@pbi.sprint.id == @project.product_backlogs.first.id) and
                       User.current.allowed_to?(:sort_product_backlog, @project))
    menu_needed = (render_move_to_last_sprint or render_move_to_product_backlog or render_move_pbi) -%>
<%- if menu_needed -%>
  <div class="modal-issue-menu">
    <%- if render_move_pbi -%>
      <%= form_tag(move_pbi_path(@pbi, :before), :method => :get, :remote => true,
                   :id => 'move_pbi_before') do %>
        <%= link_to(l(:label_move_pbi_before), '#', :onclick => "$('#move_pbi_before').submit(); return(false);") %>:
        <%= text_field_tag(:before_other_pbi, '', :size => 3) %>
        <%= javascript_tag "observeAutocompleteField('before_other_pbi', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>
      <% end %>
      <%= form_tag(move_pbi_path(@pbi, :after), :method => :get, :remote => true,
                   :id => 'move_pbi_after') do %>
        <%= link_to(l(:label_move_pbi_after), '#', :onclick => "$('#move_pbi_after').submit(); return(false);") %>:
        <%= text_field_tag(:after_other_pbi, '', :size => 3) %>
        <%= javascript_tag "observeAutocompleteField('after_other_pbi', '#{escape_javascript auto_complete_issues_path(:project_id => @project, :scope => (Setting.cross_project_issue_relations? ? 'all' : nil))}')" %>
      <% end %>
    <%- end -%>
    <%- if render_move_to_last_sprint -%>
      <%= link_to(l(:label_move_pbi_to_last_sprint), move_to_last_sprint_path(@pbi),
                  :remote => true, :method => :post, :class => "icon icon-sprint-board") %>
    <%- end -%>
    <%- if render_move_to_product_backlog -%>
      <%- @project.product_backlogs.each do |product_backlog| -%>
        <%= link_to(l(:label_move_pbi_to_name, :name => product_backlog.name),
                    move_to_product_backlog_path(@pbi, :id => product_backlog.id),
                    :remote => true, :method => :post, :class => "icon icon-product-backlog") %>
      <%- end -%>
    <%- end -%>
  </div>
<%- end -%>

<div id="popup-messages"></div>

<%= labelled_form_for @pbi, :url => update_pbi_path(@pbi), :method => :post, :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= f.hidden_field :tracker_id, :value => @pbi.tracker_id %>
  <%= f.hidden_field :sprint_id, :value => @pbi.sprint_id %>
  <%= error_messages_for 'pbi' %>
  <%= render :partial => 'scrum/edit_issue_attributes', :formats => [:html],
             :locals => {:f => f, :issue => @pbi} %>
<% end %>

app/views/scrum/_new_issue_attributes.html.erb
<%= render :partial => "scrum/issue_attributes", :formats => [:html],
           :locals => {:f => f, :issue => issue} %>

<p class="buttons">
  <%= submit_tag l(:button_create_and_continue), :name => "create_and_continue", :disable_with => l(:label_loading) %>
  <%= submit_tag l(:button_create), :name => "create", :disable_with => l(:label_loading) %>
  <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => "button" %>
</p>

app/views/scrum/_new_task_modal.html.erb
<h3 class="title"><%= @task.tracker.name %></h3>

<div id="popup-messages"></div>

<%= labelled_form_for @task, :url => create_task_path(@pbi), :remote => true do |f| %>
  <%= back_url_hidden_field_tag %>
  <%= f.hidden_field :tracker_id, :value => @task.tracker_id %>
  <%= error_messages_for "task" %>
  <%= render :partial => "scrum/new_issue_attributes", :formats => [:html],
             :locals => {:f => f, :issue => @task} %>
<% end %>

app/views/scrum/_velocity_form.html.erb
<tr>
  <td colspan="3">
    <%= form_tag(url, :method => :get, :id => 'velocity_form') do %>
      <%= hidden_field_tag(:filter_by_project, params[:filter_by_project]) %>

      <%= label_tag(:velocity_type_all) do %>
        <%= radio_button_tag(:velocity_type, 'all', 'all' == velocity_type) %>
        <%= l(:label_velocity_all_pbis, :count => sprints_count) %>
      <% end %>
      &nbsp;&nbsp;&nbsp;

      <%= label_tag(:velocity_type_only_scheduled) do %>
        <%= radio_button_tag(:velocity_type, 'only_scheduled', 'only_scheduled' == velocity_type) %>
        <%= content_tag('abbr', :title => l(:label_velocity_only_scheduled_pbis_hint)) do %>
          <%= l(:label_velocity_only_scheduled_pbis) %>
        <% end %>
      <% end %>
      &nbsp;&nbsp;&nbsp;

      <%= label_tag(:velocity_type_custom) do %>
        <%= radio_button_tag(:velocity_type, 'custom', 'custom' == velocity_type) %>
        <%= l(:label_velocity_custom) %>
      <% end %>
      <%= text_field_tag(:custom_velocity, velocity, :size => 5,
                         :onclick => "$('#velocity_type_custom').prop('checked', true);") %>
      &nbsp;&nbsp;&nbsp;

      <%= button_tag(l(:button_update)) %>
    <% end %>
  </td>
</tr>

app/views/scrum/create_pbi.js.erb
<%- if @continue or defined?(@exception) -%>
	<%- if defined?(@exception) -%>
		<%- message = l(:error_creating_pbi, :message => @exception.message)
				message_class = "error" -%>
	<%- else -%>
		$("#new_issue").each (function() {
			this.reset();
		});
		<%- message = l(:notice_pbi_created)
				message_class = "notice" -%>
	<%- end -%>
	$("#popup-messages").html("<div class=\"flash <%= message_class %>\"><%= message %></div>");
<%- else -%>
	$("#ajax-modal").dialog("close");
<%- end -%>
<%- if !defined?(@exception) -%>
	if ($("#pbis").length > 0) {
		<%- if @top -%>
			$("#pbis").prepend("<%=
				escape_javascript(render :partial => "post_its/product_backlog/pbi", :formats => [:html],
																 :locals => {:project => @project, :pbi => @pbi, :read_only => false}).html_safe
			%>");
		<%- else -%>
			$("#pbis").append("<%=
				escape_javascript(render :partial => "post_its/product_backlog/pbi", :formats => [:html],
																 :locals => {:project => @project, :pbi => @pbi, :read_only => false}).html_safe
			%>");
		<%- end -%>
	} else if ($("#sprint_board").length > 0) {
		$("#sprint_board").append("<%=
			escape_javascript(render :partial => "post_its/sprint_board/pbi_row", :formats => [:html],
															 :locals => {:project => @project, :pbi => @pbi,
																					 :task_statuses => IssueStatus.task_statuses}).html_safe
		%>");
	}
  <%- if (!(IssueStatus.pbi_statuses.include?(@pbi.status))) -%>
    $("#<%= @pbi.sprint.is_product_backlog? ? "pbi_#{@pbi.id}" : "pbi_#{@pbi.id}_row" %>").remove();
  <%- end -%>
<%- end -%>

app/views/scrum/edit_task.js.erb
$("#ajax-modal").html("<%= escape_javascript(render :partial => "scrum/edit_task_modal") %>");
showModal("ajax-modal", "800px");

app/views/scrum/new_task.js.erb
$("#ajax-modal").html("<%= escape_javascript(render :partial => "scrum/new_task_modal") %>");
showModal("ajax-modal", "800px");