config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

# Copyright © Emilio González Montaña
# Licence: Attribution & no derivates
#   * Attribution to the plugin web page URL should be done if you want to use it.
#     https://redmine.ociotec.com/projects/redmine-plugin-scrum
#   * No derivates of this plugin (or partial) are allowed.
# Take a look to licence.txt file at plugin root folder for further details.

resources :projects do
  resources :sprints, :shallow => true do
    member do
      get :edit_effort
      post :update_effort
      get :burndown
      get :burndown_graph
      get :stats
      post :sort
    end
    collection do
      get :burndown_index
      get :stats_index
    end
  end
  post "sprints/change_task_status",
       :controller => :sprints, :action => :change_task_status,
       :as => :sprints_change_task_status

  resources :product_backlog, :shallow => true do
    member do
      post :sort
      post :create_pbi
      get :burndown
      get :burndown_graph
      get :check_dependencies
      get :release_plan
    end
  end
  get "product_backlog/new_pbi/:tracker_id",
      :controller => :product_backlog, :action => :new_pbi,
      :as => :product_backlog_new_pbi

  get "scrum/stats",
      :controller => :scrum, :action => :stats,
      :as => :scrum_stats

end

post "issues/:id/story_points",
     :controller => :scrum, :action => :change_story_points,
     :as => :change_story_points
post "issues/:id/remaining_story_points",
     :controller => :scrum, :action => :change_remaining_story_points,
     :as => :change_remaining_story_points
post "issues/:id/pending_effort",
     :controller => :scrum, :action => :change_pending_effort,
     :as => :change_pending_effort
post "issues/:id/pending_efforts",
     :controller => :scrum, :action => :change_pending_efforts,
     :as => :change_pending_efforts
post "issues/:id/assigned_to",
     :controller => :scrum, :action => :change_assigned_to,
     :as => :change_assigned_to
get "issues/:id/time_entry",
     :controller => :scrum, :action => :new_time_entry,
     :as => :new_scrum_time_entry
post "issues/:id/time_entry",
     :controller => :scrum, :action => :create_time_entry,
     :as => :create_scrum_time_entry
get "scrum/:sprint_id/new_pbi/:tracker_id",
     :controller => :scrum, :action => :new_pbi,
     :as => :new_pbi
post "scrum/:sprint_id/create_pbi",
     :controller => :scrum, :action => :create_pbi,
     :as => :create_pbi
get "scrum/:pbi_id/new/:tracker_id",
    :controller => :scrum, :action => :new_task,
    :as => :new_task
post "scrum/:pbi_id/create_task",
     :controller => :scrum, :action => :create_task,
     :as => :create_task
get "scrum/:pbi_id/edit_pbi",
    :controller => :scrum, :action => :edit_pbi,
    :as => :edit_pbi
post "scrum/:pbi_id/update_pbi",
     :controller => :scrum, :action => :update_pbi,
     :as => :update_pbi
get "scrum/:pbi_id/move/:position",
    :controller => :scrum, :action => :move_pbi,
    :as => :move_pbi
get "scrum/:id/edit_task",
    :controller => :scrum, :action => :edit_task,
    :as => :edit_task
post "scrum/:id/update_task",
     :controller => :scrum, :action => :update_task,
     :as => :update_task
post "scrum/:pbi_id/move_to_last_sprint",
     :controller => :scrum, :action => :move_to_last_sprint,
     :as => :move_to_last_sprint
post "scrum/:sprint_id/move_not_closed_pbis_to_last_sprint",
     :controller => :scrum, :action => :move_not_closed_pbis_to_last_sprint,
     :as => :move_not_closed_pbis_to_last_sprint
post "scrum/:pbi_id/move_to_product_backlog",
     :controller => :scrum, :action => :move_to_product_backlog,
     :as => :move_to_product_backlog

app/views/common/_bar_chart.js.erb
<%= javascript_tag do %>
var <%= graph[:id] %>_data = [
  <%- rows.each do |name, data| -%>
  {
    key: '<%= name ? name : "---" %>',
    values: [<%= raw(data.collect{ |name, value| "{x: '#{name}', y: #{value}}" }.join(', ')) %>]
  },
  <%- end -%>
];
if (<%= graph[:id] %>_data.length > 0)
{
  nv.addGraph(function() {
    var chart = nv.models.multiBarChart()
      .color(d3.scale.category10().range())
      .reduceXTicks(false)
      .showControls(false);
    chart.tooltip.contentGenerator(function(data) {
      return '<h3>' + data.value + ' (' + data.series.length + ')</h3><p>' + data.series[0]['key'] + ': ' + data.series[0]['value'] + '</p>';
    });
    chart.yAxis.tickFormat(d3.format('.2f'));
    chart.yAxis.ticks(10);
    if (<%= graph[:id] %>_data[0].values.length > 1)
    {
      chart.margin({bottom: 100});
      chart.xAxis.rotateLabels(-30);
    }
    d3.select("#<%= graph[:id] %> svg")
      .datum(<%= graph[:id] %>_data)
      .call(chart);
    nv.utils.windowResize(chart.update);
    return chart;
  });
}
<% end %>

app/views/common/_fullscreen_content.html.erb
<div class="scrum-content">
  <div class="scrum-contextual">
    <%= link_to('',
                '#',
                :title => "#{l(:label_fullscreen)}",
                :class => 'icon icon-fullscreen',
                :onclick => "$('.scrum-content').toggleClass('scrum-content-fullscreen');") %>
    <%= link_to('',
                '#',
                :title => "#{l(:label_exit_fullscreen)}",
                :class => 'icon icon-normal-screen',
                :onclick => "$('.scrum-content').toggleClass('scrum-content-fullscreen');") %>
    <%= javascript_tag do %>
      $(document).keyup(function(event) {
        if (event.keyCode == 27) {
          $('.scrum-content').removeClass('scrum-content-fullscreen');
        }
      });
    <% end %>
  </div>
  <%= yield %>
</div>

app/views/common/_scrum_backlog_menu.html.erb
<div class="contextual scrum-menu">
  <%- if User.current.allowed_to?(:view_product_backlog, @project) -%>
    <%= link_to(l(:label_product_backlog), product_backlog_path(@product_backlog),
                :class => 'icon icon-product-backlog') %>
  <%- end -%>
  <%- if User.current.allowed_to?(:view_product_backlog_burndown, @project) -%>
    <%= link_to(l(:label_product_backlog_burndown_chart), burndown_product_backlog_path(@product_backlog),
                :class => 'icon icon-burndown') %>
  <%- end -%>
  <%- if User.current.allowed_to?(:view_release_plan, @project) -%>
    <%= link_to(l(:label_release_plan), release_plan_product_backlog_path(@product_backlog),
                :class => 'icon icon-release-plan') %>
  <%- end -%>
  <%- if User.current.allowed_to?(:manage_sprints, @project) and @product_backlog -%>
    <%= link_to('', new_project_sprint_path(@project, :back_url => url_for(params), :create_product_backlog => true),
                :class => 'icon icon-add', :title => l(:button_add)) %>
    <%= link_to('', edit_sprint_path(@product_backlog, :back_url => url_for(params)),
                :class => 'icon icon-edit', :title => l(:button_edit)) %>
    <%= link_to('', sprint_path(@product_backlog),
                {:method => :delete,
                 :data => {:confirm => l(:text_are_you_sure)},
                 :class => 'icon icon-del',
                 :title => l(:button_delete)}) %>
  <%- end -%>
  <%= render_scrum_help %>
</div>

app/views/common/_scrum_editable_value.html.erb
<input id="<%= element_id %>" type="text" class="editable-time" size="2" title="<%= title %>"
       value="<%= number_with_precision(value, precision: 2,  strip_insignificant_zeros: true) %>"
       <%= 'readonly' unless editable %>/>
<%- if defined?(unit) -%>
  <span <% if defined?(unit_title) %> title="<%= unit_title %>"<% end %>>
    <%= unit %>
  </span>
<%- end -%>
<%- if editable -%>
  <%= javascript_tag do %>
    $(document).ready(function() {
      $("#<%= element_id %>").change(function() {
        if ($.isFunction($.fn.setupAjaxIndicator)) {
          setupAjaxIndicator();
        }
        $.ajax({
          url: "<%= change_element_path %>",
          type: "POST",
          data: {value: $(this).val()},
          error: function() {
            alert("<%= l(:error_changing_value) %>");
          },
          complete: function() {
            if ($.isFunction($.fn.hideOnLoad)) {
              hideOnLoad();
            }
          }
        });
      });
    });
  <% end %>
<%- end -%>

app/views/common/_scrum_footer.html.erb
<%= javascript_tag do %>
  $(document).ready(function() {
    <%- link = link_to(l(:label_scrum), Redmine::Plugin::registered_plugins[:scrum].url)
        author = Redmine::Plugin::registered_plugins[:scrum].author
        copy_right = link_to("©", "http://creativecommons.org/licenses/by-nd/4.0/")
        legend = "Powered by #{link} plugin #{copy_right} 2013-2015 #{author}" -%>
    $("#footer").append('<div class="bgl"><div class="bgr"><%= raw legend %></div></div>');
  });
<% end %>

app/views/common/_scrum_pending_effort.html.erb
<%- if User.current.allowed_to?(:view_pending_effort, project) or
       User.current.allowed_to?(:edit_pending_effort, project) -%>
  <%= render :partial => "common/scrum_editable_value",
             :locals => {:project => project,
                         :title => l(:field_pending_effort),
                         :element_id => "pending_effort_#{task.id}",
                         :value => task.pending_effort,
                         :unit => "h",
                         :unit_title => l(:field_pending_effort),
                         :editable => (User.current.allowed_to?(:edit_sprint_board, project) and
                                       User.current.allowed_to?(:edit_pending_effort, project) and
                                       task.editable?),
                         :change_element_path => change_pending_effort_path(task)} %>
<%- end -%>

app/views/common/_scrum_remaining_story_points.html.erb
<%= render :partial => "common/scrum_editable_value",
           :locals => {:title => l(:label_remaining_story_point_plural),
                       :element_id => "remaining_story_points_#{pbi.id}",
                       :value => pbi.remaining_story_points,
                       :unit => l(:label_remaining_story_point_unit),
                       :unit_title => l(:label_remaining_story_point_plural),
                       :editable => (User.current.allowed_to?(:edit_issues, pbi.project) and
                                     pbi.editable? and !read_only),
                       :change_element_path => change_remaining_story_points_path(pbi)} %>

app/views/common/_stat_graph_and_table.html.erb
<table class="scrum-stats-chart-table">
  <tr>
    <td align="right">
      <svg id="<%= graph[:id] %>"
           style="width: <%= graph[:width] %>px; height: <%= graph[:height] %>px;">
      </svg>
    </td>
    <td align="left">
      <table class="scrum-stats-table">
        <thead>
        <tr>
          <th align="left"><%= element[:label] %></th>
          <th align="center"><%= unit[:plural_label] %></th>
          <th align="center">%</th>
        </tr>
        </thead>
        <tbody>
        <%- rows.each do |row| -%>
            <tr>
              <td align="left"><%= row[element[:name]].nil? ? "---" : row[element[:name]] %></td>
              <td align="center"><%= "#{row[:total].round(2)} #{unit[:label]}" %></td>
              <td align="center"><%= "#{row[:percentage].round}%" %></td>
            </tr>
        <%- end -%>
        <tr>
          <td align="left" class="total"><%= l(:label_total) %></td>
          <td align="center" class="total"><%= "#{total.round(2)} #{unit[:label]}" %></td>
          <td align="center" class="total">100%</td>
        </tr>
        </tbody>
      </table>
    </td>
  </tr>
</table>
<%= render :partial => "sprints/pie_chart",
           :formats => [:js],
           :locals => {:graph => graph,
                       :element => element,
                       :rows => rows} %>